import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

/**
 * Lab4.PACKAGE_NAME
 * thomasroseman on 2/8/16
 */
public class problem3 {

    private JPanel base;
    private JButton searchButton;
    private JTextField textFieldA;
    private JTextField textFieldB;
    private JTextField textFieldC;
    private JTextField textFieldD;
    private JTextField textFieldE;
    private JTextField textFieldF;
    private JLabel rootLabel;
    private JLabel minLabel;
    private JLabel maxLabel;

    private int a, b, c, d, e, f;
    private int root = 1;

    private int random;
    private Random r = new Random();

    public problem3() {
        searchButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                getValues();
                System.out.println("Clicked");

                /*while (root != 0){
                    System.out.println("Looping");
                        if (functiony(getRandom()) == 0){
                            root = 0;
                        }
                }*/

                for (int i = -5000; i <= 5000; i++) {
                    if (functiony(i) == 0) {
                        System.out.println("Found root");
                        i = 50001;
                    }
                }

            }
        });
    }

    private double functiony(int x) {
        System.out.println(a * Math.pow(x, 9) + b * Math.pow(x, 7) + c * Math.pow(x, 5) + d * Math.pow(x, 3) + e * x + f);
        return a * Math.pow(x, 9) + b * Math.pow(x, 7) + c * Math.pow(x, 5) + d * Math.pow(x, 3) + e * x + f;
    }

    private int getRandom() {
        return 5000 - r.nextInt(5001);
    }

    private void getValues() {
        a = Integer.parseInt(textFieldA.getText());
        b = Integer.parseInt(textFieldB.getText());
        c = Integer.parseInt(textFieldC.getText());
        d = Integer.parseInt(textFieldD.getText());
        e = Integer.parseInt(textFieldE.getText());
        f = Integer.parseInt(textFieldF.getText());
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("problem3");
        frame.setContentPane(new problem3().base);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        base = new JPanel();
        base.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        base.add(spacer2, gbc);
        minLabel = new JLabel();
        minLabel.setText("Min");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        base.add(minLabel, gbc);
        maxLabel = new JLabel();
        maxLabel.setText("Max");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        base.add(maxLabel, gbc);
        textFieldA = new JTextField();
        textFieldA.setPreferredSize(new Dimension(44, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(textFieldA, gbc);
        textFieldB = new JTextField();
        textFieldB.setPreferredSize(new Dimension(44, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(textFieldB, gbc);
        textFieldC = new JTextField();
        textFieldC.setPreferredSize(new Dimension(44, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(textFieldC, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(spacer4, gbc);
        textFieldD = new JTextField();
        textFieldD.setPreferredSize(new Dimension(44, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(textFieldD, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(spacer5, gbc);
        textFieldE = new JTextField();
        textFieldE.setPreferredSize(new Dimension(44, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(textFieldE, gbc);
        textFieldF = new JTextField();
        textFieldF.setPreferredSize(new Dimension(44, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(textFieldF, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(spacer7, gbc);
        searchButton = new JButton();
        searchButton.setText("Search");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        base.add(searchButton, gbc);
        rootLabel = new JLabel();
        rootLabel.setText("Root");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        base.add(rootLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return base;
    }
}
